# Generated by Django 2.0.2 on 2018-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0002_auto_20180206_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='body',
            field=models.TextField(default='NULL', help_text='Body of Article'),
        ),
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.TextField(default='NULL', help_text='Title of Article'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='stance',
            field=models.CharField(default='NULL', help_text='Stance of Title in relation to Body', max_length=20),
        ),
    ]
