# Generated by Django 2.0.2 on 2018-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.TextField(help_text='Url of the Article', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username of User', max_length=20, primary_key=True, serialize=False),
        ),
    ]
