# Generated by Django 2.0.2 on 2018-02-07 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0005_auto_20180207_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorer.User'),
        ),
    ]
