# Generated by Django 2.0.2 on 2018-02-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0006_paper_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(max_length=20)),
                ('referree', models.CharField(max_length=20)),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorer.Paper')),
            ],
        ),
    ]
