# Generated by Django 2.0.2 on 2018-02-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0007_paperuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperuser',
            name='referree',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='paperuser',
            name='referrer',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='paperuser',
            name='url',
            field=models.TextField(default='NULL'),
        ),
    ]
